# Generated by Django 4.0.4 on 2022-05-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtoken', models.CharField(max_length=1000)),
                ('qsno', models.IntegerField()),
                ('qbno', models.IntegerField(default=0)),
                ('nextlink', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temail', models.EmailField(max_length=1000)),
                ('tcode', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=300)),
                ('tbno', models.IntegerField(default=0)),
                ('tdone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtoken', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('isvalid', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
        ),
    ]
